global attributes
esm-tools/pymorize pull request #23
Opened 2024-07-25 08:49 UTC by siligam

addresses issue #16

2025-01-10 14:20 UTC, pgierz requested changes
This is a good start. There are a few things major changes and several minor ones I think would be good to address:

### Major Changes
1. At the moment, you are accessing a module-level dictionary, `data`. I would prefer that this comes from the user somehow, so you would need to integrate it into the `CMORizer` object and pass the that to the `Rule`. We already have `assign_data_request_to_rule` (or something like that) so you can copy that behaviour.
2. ~I would, where possible, move the logic to extract global level attributes that you get from the `DataRequestVariable` directly to the `DataRequestVariable` object.~ In the end, something like this would be nice:
```python
>>> ds = xr.Dataset(...)
>>> rule = Rule(...)
>>> rule.data_request_variable
<DataRequestVariable object at ...>
>>> # Assume that during post-initialisation, something creates a rule attribute file_level_attrs as a dictionary
>>> fla = rule.file_level_attrs
>>> fla
{"institution_id": "AWI", ...}
>>> ds.attrs.update(fla)
```
So, in a pipeline step, this would look like this:
```python
def set_file_level_attrs(ds, rule):
    fla = rule.file_level_attrs
    ds.attrs.update(fla)
    return ds
```
To refresh how this looks like in NetCDF, one can look at the pi mesh test data from FESOM2
```
$ ncdump -h u.fesom.1985.nc
netcdf u.fesom.1985 {
dimensions:
        nz1 = 47 ;
        elem = 5839 ;
        time = UNLIMITED ; // (1 currently)
variables:
        double nz1(nz1) ;
                nz1:long_name = "depth at layer midpoint" ;
                nz1:units = "m" ;
                nz1:positive = "down" ;
                nz1:axis = "Z" ;
        double time(time) ;
                time:long_name = "time" ;
                time:standard_name = "time" ;
                time:units = "seconds since 1985-01-01 0:0:0" ;
                time:axis = "T" ;
                time:stored_direction = "increasing" ;
        float u(time, nz1, elem) ;
                u:description = "zonal velocity" ;
                u:long_name = "zonal velocity" ;
                u:units = "m/s" ;
                u:location = "face" ;
                u:mesh = "fesom_mesh" ;

// global attributes:
                :Conventions = "UGRID-1.0" ;
                :FESOM_model = "FESOM2" ;
                :FESOM_website = "fesom.de" ;
                :FESOM_git_SHA = "e900ff01" ;
                :FESOM_MeshPath = "/pool/data/AWICM/FESOM2/MESHES_FESOM2.1/pi/" ;
                :FESOM_mesh_representative_checksum = "" ;
                :FESOM_ClimateDataPath = "/pool/data/AWICM/FESOM2/INITIAL/phc3.0/" ;
                :FESOM_which_ALE = "zstar" ;
                :FESOM_mix_scheme = "KPP" ;
                :FESOM_use_partial_cell = 0 ;
                :FESOM_force_rotation = -1 ;
                :FESOM_include_fleapyear = -1 ;
                :FESOM_use_floatice = 0 ;
                :FESOM_whichEVP = 1 ;
                :FESOM_evp_rheol_steps = 120 ;
                :FESOM_opt_visc = 7 ;
                :FESOM_use_wsplit = -1 ;
                :FESOM_autorotate_back_to_geo = -1 ;
} 

```


### Minor Changes
1. Docstrings for many of the functions are missing
2. You committed some files with your working notes. We don't want those in the repository at the end, or, they should be included in the user handbook.
3. Some changes in the YAML files where you changed a key (e.g. `source_id`), still have the old value as a comment. This makes the diffs unclean, so I would rather you just directly change things.
4. The inclusion in the standard pipeline should happen before manual checkpointing. The manual checkpoint trigger should be directly before computation is called.

2025-01-10 14:20 UTC, pgierz commented on src/pymorize/global_attributes.py
> +    cv = data["source_id"][source_id]
Here is `data` again. To be replaced from a more modular way of getting CVs

2025-01-20 10:05 UTC, pgierz requested changes
This is on the right track, I have some improvement suggestions.

There were some comments from my last review that need to be addressed still, too.

2025-01-20 10:05 UTC, pgierz commented on src/pymorize/global_attributes.py
> +    def _source_id_related(self, rule: dict) -> dict:
Please add a doc-string and some examples here, this is a big enough function to deserve some testing.

2025-01-20 10:05 UTC, pgierz commented on src/pymorize/global_attributes.py
> +        grid = model_components[model_component]["description"]
Are you sure about this one? `grid` is the model component's description?

2025-01-20 11:23 UTC, siligam commented on src/pymorize/global_attributes.py
> +        grid = model_components[model_component]["description"]
It is a bit unclear what should be the value for this from the documentation. This needs to be cross-checked with previously generated output from (maybe) seamore tool.

2025-01-21 11:23 UTC, pgierz commented on src/pymorize/global_attributes.py
> +            if len(cv_institution_ids) > 1:
Maybe we can make it abundantly clear here and do something like:

```suggestion
            if isinstance(inst_id, list) and len(cv_institution_ids) > 1:
```
Lower down, you could also do an instance check for list. That would avoid problems with you accidentally getting a string, or something like that.

...just an idea.

2025-01-24 08:57 UTC, siligam commented on src/pymorize/global_attributes.py
> +    def _source_id_related(self, rule: dict) -> dict:
this attributed is renamed to `attrs_map_on_rule` to avoid confusion.

2025-01-24 09:03 UTC, siligam commented on src/pymorize/global_attributes.py
> +            if len(cv_institution_ids) > 1:
`cv_institution_ids` is the institution_ids from CMIP6 CVs. To do a `isinstance` check for `list` in other terms mean checking the schema defined in json for this field. This can be done for all the fields but it steers the focus on a different direction. What make sense is to have module that does schema checking but should that be a part of pymorize. Data source schema validation. plz comment

2025-02-12 15:10 UTC, pgierz requested changes
Almost there @siligam, good work. There are still some things to be cleaned up, see the comments below.

2025-02-12 15:10 UTC, pgierz commented on src/pymorize/global_attributes.py
> +        d["realm"] = " ".join(header.realm) if header.realm else header.realm
this line makes no sense to me. Don't you want something like this:
```suggestion
        d["realm"] = " ".join(header.realm) if isinstance(header.realm, list) else header.realm
```

2025-02-12 15:10 UTC, pgierz commented on src/pymorize/global_attributes_checklist.org
Please remove this file from the PR!

2025-02-12 15:10 UTC, pgierz commented on src/pymorize/metadata_attrs.py
This comment has not yet been addressed.

2025-02-12 15:10 UTC, pgierz commented on src/pymorize/pipeline.py
> +        #"pymorize.global_attributes.set_global_attributes",
Why is this step commented out? Also, this should happen before the checkpoint, not after

2025-02-12 15:10 UTC, pgierz commented on src/pymorize/cmorizer.py
> +        #self._post_init_populate_global_attributes()
Why is this commented out?

2025-02-13 07:10 UTC, mandresm commented on src/pymorize/cmorizer.py
> +        #self._post_init_populate_global_attributes()
Because the global attributes are set in the pipeline, not as a `_post_init` job, right @siligam?

2025-02-13 07:30 UTC, mandresm requested changes
Okay, so I've had a look at it. There is a bit to clean and generalize. On my comments I specify which ones I'm going to be working on.

I suggest the following: we reply to the different comments to assign ourselves what are we working on. We respond to comments one at a time so that we don't block each other @siligam

2025-02-13 07:30 UTC, mandresm commented on src/pymorize/cmorizer.py
> +        `<tables_dir>/CMIP6_CVs` and stores them in the `controlled_vocabularies`
```suggestion
        ``<tables_dir>/CMIP6_CVs`` and stores them in the ``controlled_vocabularies``
```

If readthedocs uses rst, then what you are looking for is double quotes, single just make coursive.

2025-02-13 07:30 UTC, mandresm commented on src/pymorize/cmorizer.py
> +        self.controlled_vocabularies = ControlledVocabularies.new_from_dir(cv_dir)
This is CMIP6-specific, I'll try to generalize it, and test it today or tomorrow.

2025-02-13 07:30 UTC, mandresm commented on src/pymorize/cmorizer.py
> +
If I understood it right, this can be deleted, correct?

```suggestion
```

2025-02-13 07:30 UTC, mandresm commented on src/pymorize/data_request/variable.py
> +        return self.ga.get_global_attributes(self.rule_attrs, self.table_header)
Is this still needed or can it be removed?

2025-02-13 07:30 UTC, mandresm commented on src/pymorize/data_request/variable.py
> +
I think this can be removed

```suggestion

    def set_global_attributes(self, cv, rule_attrs):
        self.ga = GlobalAttributes(cv)
        self.rule_attrs = rule_attrs

```

2025-02-13 07:30 UTC, mandresm commented on src/pymorize/global_attributes_checklist.org
can be done as a last cleanup step. I'm adding it in the TODO of this PR.

2025-02-13 07:30 UTC, mandresm commented on src/pymorize/metadata_attrs.py
> +def set_global_attrs(data: xr.Dataset, rule):
I don't this this is used anywhere, so it can be removed

2025-02-13 07:30 UTC, mandresm commented on src/pymorize/metadata_attrs.py
> +    global_attrs = data.drv.global_attrs(override_dict=global_attrs)
We need to keep this functionality if we are removing this method. So let's move this line to the `set_global_attributes` method in `global_attributes.py` if possible and reasonable.

2025-02-13 07:30 UTC, mandresm commented on src/pymorize/pipeline.py
> +        #"pymorize.global_attributes.set_global_attributes",
Yeap, agreed.

2025-02-13 07:40 UTC, siligam commented on src/pymorize/global_attributes.py
> +    def _tracking_id(self, attrs_map_on_rule=None) -> dict:
the second arguments is not required but it is placed there to have a consistent function calling  signature with other functions. `def func(self, attrs_map_on_rule)`.

2025-02-13 09:03 UTC, mandresm commented on src/pymorize/cmorizer.py
> +
Working on this now.

2025-02-13 09:17 UTC, mandresm commented on src/pymorize/data_request/variable.py
> +        return self.ga.get_global_attributes(self.rule_attrs, self.table_header)
working on this now

2025-02-13 09:18 UTC, mandresm commented on src/pymorize/data_request/variable.py
> +
and also working on this now

2025-02-13 09:23 UTC, mandresm commented on src/pymorize/metadata_attrs.py
> +def set_global_attrs(data: xr.Dataset, rule):
working on this

2025-02-13 09:26 UTC, mandresm commented on src/pymorize/pipeline.py
> +        #"pymorize.global_attributes.set_global_attributes",
working on this

2025-02-13 11:03 UTC, pgierz commented on src/pymorize/global_attributes.py
> +    def _tracking_id(self, attrs_map_on_rule=None) -> dict:
That's fine.

2025-02-13 12:28 UTC, mandresm commented on src/pymorize/cmorizer.py
> +        #self._post_init_populate_global_attributes()
sorted!

2025-02-13 12:29 UTC, mandresm commented on tests/unit/test_global_attributes.py
> +}
Define actual values for them to be asserted.

2025-02-13 12:30 UTC, mandresm commented on tests/unit/test_global_attributes.py
> +}
I am working on this now

2025-02-13 13:30 UTC, mandresm commented on tests/unit/test_global_attributes.py
> +}
sorted!

2025-02-13 13:41 UTC, mandresm commented on src/pymorize/pipeline.py
> +        "pymorize.global_attributes.set_global_attributes",
done!

2025-02-13 13:44 UTC, mandresm commented on src/pymorize/cmorizer.py
> +        # self._post_init_populate_global_attributes()
Remove this:

```suggestion
```

2025-02-18 14:24 UTC, mandresm commented on src/pymorize/controlled_vocabularies.py
> +        return obj
Sorted

2025-02-18 14:25 UTC, mandresm commented on src/pymorize/cmorizer.py
> +        self.controlled_vocabularies = ControlledVocabularies.new_from_dir(cv_dir)
Sorted

2025-02-20 10:35 UTC, mandresm requested changes

2025-02-20 10:35 UTC, mandresm commented on src/pymorize/global_attributes.py
> +class GlobalAttributes:
Make use of a factory here for `CMIP6GlobalAttributes`. I will take care of that.

2025-02-20 12:06 UTC, siligam commented on src/pymorize/rule.py
> +        )
@mandresm this change pretty much depends on how information is provided in the `sample.yaml` and how the rule ingests them. Method `global_attributes_set_on_rule` on rule is just trying to retrieve this information from rule object. 

Some of the optional fields may become mandatory if it has multiple values. For instance, if more than one institution participates in a MIP, then it is expected that the user provides `institution_id` explicitly in the `sample.yaml`.   So, separating the `required` and `optional` fields into mapping has value if the code down the stream has advantage in doing so. At the moment, the downstream code always checks for multiple values for optional fields and raises an error asking the user to provide specific value, if it has multiple values.

Did you have any specific reason for this suggestion?

2025-02-20 12:49 UTC, mandresm commented on src/pymorize/rule.py
> +        )
> this change pretty much depends on how information is provided in the sample.yaml and how the rule ingests them. Method global_attributes_set_on_rule on rule is just trying to retrieve this information from rule object.

I see, so this are attributes that belong to the rule, our tool and the `config.yaml`, not to any specific MIP. That means that in CMIP7 we will still have them.

> So, separating the required and optional fields into mapping has value if the code down the stream has advantage in doing so. At the moment, the downstream code always checks for multiple values for optional fields and raises an error asking the user to provide specific value, if it has multiple values.

I see, so then let's keep it simple, as it is. Thanks for the clarification! I'm resolving this topic.

2025-02-20 13:34 UTC, mandresm commented on src/pymorize/global_attributes.py
> +class GlobalAttributes:
Done!

2025-02-21 10:21 UTC, mandresm commented on src/pymorize/global_attributes.py
> +            if len(cv_institution_ids) > 1:
@pgierz, please comment :)

2025-02-21 10:27 UTC, mandresm commented on src/pymorize/global_attributes.py
> +            if len(cv_institution_ids) > 1:
IMO I agree with @siligam, there is no need to check for list, since we know it's defined as a list in the json files. If I understand your suggestion @siligam correctly, I would not control with a schema the json files provided by CMIP. It would be a nice-to-have but quite some work to write it all down.

2025-02-21 10:28 UTC, mandresm commented on src/pymorize/global_attributes.py
> +                    "Please specify one in the rule."
```suggestion
                    "Please specify a ``institution_id`` in the rule."
```
So that they know which particular key they should be using.

2025-02-24 09:54 UTC, mandresm requested changes
@siligam, can you please go through the different change requests and solve them? They are just some minimal changes. Other than that this is finished! :)

@pgierz and @siligam, can someone of you check what's going on with the testing and fix it?

2025-02-24 09:54 UTC, mandresm commented on src/pymorize/global_attributes_checklist.org
> +* GLOBAL ATTRIBUTES
This file can be removed now.

2025-02-24 09:54 UTC, mandresm commented on src/pymorize/global_attributes.py
> +        # breakpoint()
Can this comment be cleaned up now?

2025-02-27 11:12 UTC, pgierz submitted a review, later dismissed
Tests pass, this is going in now.

2025-02-27 11:23 UTC, mandresm submitted a review, later dismissed

2025-02-27 11:30 UTC, pgierz approved these changes

2025-02-27 11:37 UTC, merged

2025-02-27 15:07 UTC, mandresm commented
Awesome! :D