FESOM Regridding
esm-tools/pymorize pull request #52
Opened 2024-11-04 15:48 UTC by pgierz

# Summary

@chrisdane wanted FESOM regridding to a regular grid. This PR incorporates `pyfesom2` and uses
it's internal tools to convert to a regular grid via nearest neighbor interpolation. You should
specify the grid description (probably best to do this in the `inherit` section of the config), and add the pipeline
to the steps you want to take. Provides both a step to include in custom pipelines as well as a pre-built pipeline that performs
the regridding step

## TODO:
- [ ] Better documentatio
- [ ] test cases with verification

### Commits:

- **ci: testing now also covers doctests in code**
- **wip: fesom regridding, not yet done...**
- **wip: removes breakpoint**

2024-11-07 16:38 UTC, pgierz commented
# Updated CoPilot Summary

This pull request introduces several changes to integrate FESOM (Finite-Element/volumetric Sea-Ice Ocean Model) functionality into the project. The key changes include updates to CI workflows, new dependencies, and the addition of FESOM-specific regridding functionality. Additionally, there are several updates to the testing framework to accommodate the new features.

### CI Workflow Enhancements:
* Added steps to checkout LFS (Large File Storage) files and verify mesh files in the CI workflow (`.github/workflows/CI-test.yaml`).
* Updated the package installation command to include the `fesom` extra dependencies (`.github/workflows/CI-test.yaml`).

### Dependency Management:
* Added a new submodule for FESOM mesh files in `.gitmodules`.
* Added `pyfesom2` as a dependency under the `fesom` extra in `setup.py`.

### New FESOM Functionality:
* Introduced a new module `fesom.py` with functions for regridding FESOM data and a new pipeline class `FESOMRegridPipeline` (`src/pymorize/fesom.py`).
* Enhanced the `FrozenPipeline` class to support named pipelines and steps (`src/pymorize/pipeline.py`). [[1]](diffhunk://#diff-899aef304e213d8841d53cf1be180288fd2fec7a9421370d233b5d437c43bb54R182-R184) [[2]](diffhunk://#diff-899aef304e213d8841d53cf1be180288fd2fec7a9421370d233b5d437c43bb54R193-R196) [[3]](diffhunk://#diff-899aef304e213d8841d53cf1be180288fd2fec7a9421370d233b5d437c43bb54L213-R220) [[4]](diffhunk://#diff-899aef304e213d8841d53cf1be180288fd2fec7a9421370d233b5d437c43bb54L242-R246)

### Testing Enhancements:
* Added new test configurations and fixtures for FESOM mesh and output files (`tests/configs/fesom_pi_mesh_run.yaml`, `tests/fixtures/config_files.py`, `tests/fixtures/configs.py`, `tests/fixtures/datasets.py`). [[1]](diffhunk://#diff-c4188a3b7d7e61883473ae0aaf890d24ba8ffc9ad9669ca097e29e11795710c6R1-R12) [[2]](diffhunk://#diff-33a35ab7264d90eb730ed40821a952dbbff75755123482581bcc099a2e7a54a1R9-R13) [[3]](diffhunk://#diff-071d0e16597702b13688eedcdb69f2a7f61ea4200c6ee425ea480cc8fe30da52R2) [[4]](diffhunk://#diff-071d0e16597702b13688eedcdb69f2a7f61ea4200c6ee425ea480cc8fe30da52R41-R46) [[5]](diffhunk://#diff-6cb8227a57d0ad5123bab4b555c691c65c46ca424671e45dbeaf7f3cc482fc09R1-R11)
* Created unit tests for FESOM functionality (`tests/externals/test_pyfesom2.py`, `tests/unit/test_fesom.py`). [[1]](diffhunk://#diff-27fe283736c60d07322fe9e8cedf8e60d13efe14f7152d8b40d74455fc3e0863R1-R16) [[2]](diffhunk://#diff-e8cf1902b82a655e474a645294eb952af30ebb28ec8cb8b3252d661f3809466bR1-R22)

2024-11-07 16:49 UTC, pgierz commented
Documentation Preview: https://pymorize.readthedocs.io/en/feat-fesom-regridding/pymorize_fesom.html

2025-01-09 15:55 UTC, pgierz commented
#77 should go in first and this one should get rewritten.

2025-04-02 12:38 UTC, pgierz commented
This is ready for review

2025-04-03 10:57 UTC, mandresm requested changes
Only one comment after a shallow review

2025-04-03 10:57 UTC, mandresm commented on src/pymorize/fesom_2p1/regridding.py
> +    x = np.linspace(x_min, x_max, int(x_max - x_min))
Where is the regular grid resolution defined and how does the user define it in the config yaml?

2025-04-03 13:04 UTC, pgierz commented on src/pymorize/fesom_2p1/regridding.py
> +    x = np.linspace(x_min, x_max, int(x_max - x_min))
This is a bit clunky, I agree. By default it does 1˚x1˚, globally. I think it might be better to instead support something like CDO has, so `r360x180` for 1˚x1˚ or `r720x360` for 0.5˚x0.5˚.

2025-04-03 14:35 UTC, mandresm commented on src/pymorize/fesom_2p1/regridding.py
> +    x = np.linspace(x_min, x_max, int(x_max - x_min))
So with the current implementation I could simply set `box: "-360, 360, -180, 180"` to get a 0.5 degree resolution? It is not very pythonic but if this is what the users are used to fair enough. I would have expected to simply define a lat and lon resolution instead.

2025-04-08 11:46 UTC, pgierz commented on src/pymorize/fesom_2p1/regridding.py
> +    x = np.linspace(x_min, x_max, int(x_max - x_min))
I believe so, yes. Basically, the justification for this way of writing it down is "it does the same thing as pyfesom2"

2025-04-09 19:55 UTC, siligam approved these changes

2025-04-10 09:46 UTC, merged