Test/save_dataset
esm-tools/pymorize pull request #72
Opened 2024-11-19 09:17 UTC by siligam

# Thank you for contributing! 🎉

## Summary of the most important changes
- tests driven approach to refine saving dataset process
- Allows saving dataset with single timestep #61
- time_range used in file names conforms to CMIP guide lines.
- Avoids unnecessary data resampling.

## Usage example in the PR

Please put a small usage example in the PR body so that we can see what you want to do.

These sorts of examples should also be in the docstrings of your code!

## Checklist
+ [ x] I have tested the changes in this PR.
+ [ ] I have updated the documentation.
+ [ ] If I have made a new step which requires new arguments, these are added to the `validate.py` file 
      so that the user can see documentation for the arguments.

## Copilot Summary
If you have Github Co-Pilot, please include an automatically generated summary.

2024-11-21 09:41 UTC, pgierz requested changes
This looks good, but I have some questions and suggestions that you could have a look at.

2024-11-21 09:42 UTC, pgierz commented
I'd also like to have @mandresm read through these changes to see that he understands them as well.

2024-11-21 11:59 UTC, siligam commented on src/pymorize/files.py
you are right, I know they do not belong here and need to be relocated to something like `dataset_helpers.py` as you suggested but my first priority was also test those helper functions along with the main tests to get the logic in the helper function right so i can use them to get `time_axis_label` instead of assuming time axis is always labelled `time`.  There are couple of places in the code base where I hard coded `da.time` and they now be replaced with something like `da[time_label]`.

2024-11-21 11:59 UTC, siligam commented on src/pymorize/files.py
> +    return False
when time is of type `cftime`, the dtype of `da.data` is an `object` and so `np.issubdtype` throws a `TypeError`. In this case reaching out for the first element in the array for `isinstance` checking

2024-11-21 11:59 UTC, siligam commented on src/pymorize/files.py
> +    return (start + offset) < end
If I understand it correctly, that is handled in time averaging step. This one is checking if the data needs to be split into multiple files based on the `timespan` parameter. Lets say a 10 year data with daily interval is time averaged to monthly interval, the user can decide to write the data to a single file or split into multiple files based on the `timespan` parameter.

2024-11-21 11:59 UTC, siligam commented on src/pymorize/files.py
> +    return label.popleft()
okay. will add examples.

2024-11-21 12:29 UTC, siligam commented on src/pymorize/files.py
> +    return False
the documentation string for this function is a bit misleading. It should omit `arr` begin xr.DataArray and strictly restrict `arr` begin a `np.array`. The reason begin, if `xr.DataArray` is passed, this function then needs to figure out the label used for time axis. I will update the documentation accordingly.

2024-11-25 10:32 UTC, pgierz requested changes
Some last cleanup, see suggested changes.

2024-11-25 10:32 UTC, pgierz commented on src/pymorize/files.py
> +    #     return f"{start.strftime('%Y%m%d%H%M%S')}-{end.strftime('%Y%m%d%H%M%S')}"
I would omit this entirely, if we need it back we can check in the git history:

```suggestion
```

2024-11-25 10:32 UTC, pgierz commented on src/pymorize/frequency.py
> +# Frequency.ALL = ALL
Same here (this one is from me anyway...)
```suggestion
```

2024-11-25 10:32 UTC, pgierz commented on tests/integration/test_fesom_2p6_pimesh_esm_tools.py
> +    pipeline["steps"][:] = steps
I guess this did not make a difference, so I would prefer to keep the original version:
```suggestion
    pipeline["steps"] = steps
```

2024-11-25 10:33 UTC, pgierz commented
# Copilot Summary
This pull request includes several important changes to the `pymorize` package, focusing on improving configuration handling, enhancing dataset processing, and updating testing workflows. The most significant changes are grouped into configuration handling improvements, dataset processing enhancements, and testing workflow updates.

### Configuration Handling Improvements:
* [`src/pymorize/cmorizer.py`](diffhunk://#diff-9deea47805fe528815a5e35850622c720823cb8c6abd547246359d9502aae47aR1): Added `copy` import and modified `_post_init_attach_pymorize_config_rules` to use `copy.deepcopy` for configuration to ensure rules get independent copies of the configuration. [[1]](diffhunk://#diff-9deea47805fe528815a5e35850622c720823cb8c6abd547246359d9502aae47aR1) [[2]](diffhunk://#diff-9deea47805fe528815a5e35850622c720823cb8c6abd547246359d9502aae47aL264-R266)
* [`src/pymorize/config.py`](diffhunk://#diff-8bebb1964e5f902f42f1f89d86b48cef7d9f92ae6dba5b5999a4bda2b1272d18L47-R65): Updated example code to use `yaml.dump` for writing configuration files, ensuring proper YAML formatting.

### Dataset Processing Enhancements:
* [`src/pymorize/cmorizer.py`](diffhunk://#diff-9deea47805fe528815a5e35850622c720823cb8c6abd547246359d9502aae47aL176-R177): Modified `_post_init_populate_rules_with_tables` to use `tbl.table_id` instead of `tbl` for adding tables to rules.
* [`src/pymorize/cmorizer.py`](diffhunk://#diff-9deea47805fe528815a5e35850622c720823cb8c6abd547246359d9502aae47aL454-R472): Updated `_parallel_process_dask` to use deep copies of rules before processing to avoid unintended modifications.
* [`src/pymorize/files.py`](diffhunk://#diff-de1850897ca51b1fc9a601fd5f0bedaa9eea4ced7516cf29af1970b8b0898d0eR5-R56): Added functions to handle time label precision in file names and updated file path creation to ensure directories are created if they do not exist. [[1]](diffhunk://#diff-de1850897ca51b1fc9a601fd5f0bedaa9eea4ced7516cf29af1970b8b0898d0eR5-R56) [[2]](diffhunk://#diff-de1850897ca51b1fc9a601fd5f0bedaa9eea4ced7516cf29af1970b8b0898d0eL21-R146) [[3]](diffhunk://#diff-de1850897ca51b1fc9a601fd5f0bedaa9eea4ced7516cf29af1970b8b0898d0eL82-R157) [[4]](diffhunk://#diff-de1850897ca51b1fc9a601fd5f0bedaa9eea4ced7516cf29af1970b8b0898d0eR169-R222)

### Testing Workflow Updates:
* [`.github/workflows/CI-test.yaml`](diffhunk://#diff-934e54e4b7917e077b454ad2e154a0fa8a141813adb3f876d946d7ce42c3e8afR47-R61): Added `PREFECT_SERVER_EPHEMERAL_STARTUP_TIMEOUT_SECONDS` environment variable to ensure sufficient startup time for Prefect server during tests.
* [`tests/integration/test_fesom_2p6_pimesh_esm_tools.py`](diffhunk://#diff-8addc2dc9fd857b184c2199a63e1da5b9dda08b4bbe4bc3f4592feec38a48376R13): Marked a test as skipped to investigate a segmentation fault issue.

These changes collectively improve the robustness and reliability of the `pymorize` package, particularly in handling configurations and processing datasets.

2024-11-25 11:38 UTC, pgierz submitted a review, later dismissed

2024-11-25 12:54 UTC, merged