fesom1 to levels
esm-tools/pymorize pull request #77
Opened 2024-11-20 12:04 UTC by pgierz

## Summary of the most important changes
Allows interpolation of data on `(time, nodes_3d)` to `(time, nodes_2d, depth)`. Use the step `pymorize.fesom_1p4.nodes_to_levels`.

## Checklist
+ [x] I have tested the changes in this PR. (by hand)
+ [x] I have updated the documentation.

## Copilot Summary
If you have Github Co-Pilot, please include an automatically generated summary.

2024-11-20 13:03 UTC, pgierz commented
This pull request introduces significant enhancements and new features to the `pymorize` project, particularly in the `cli.py` and `nodes_to_levels.py` files. The changes include adding new dependencies, restructuring the CLI commands, and implementing a new module for converting FESOM 1.4 output data.

### New Dependencies:
* Added `joblib` and `numpy` to the list of dependencies in `setup.py`.

### CLI Enhancements:
* Introduced a new `scripts` command group in `src/pymorize/cli.py` to organize related commands.
* Added a new subcommand `fesom1` under the `scripts` group for FESOM-related operations.
* Registered the new `scripts` command group with the main CLI.

### New Module for FESOM 1.4:
* Created a new module `nodes_to_levels.py` in `src/pymorize/fesom_1p4/` that provides functionality to convert FESOM 1.4 output data from (nodes, time) to (nodes, levels, time). This includes:
  * Functions for opening, processing, and saving datasets using Xarray.
  * A function to interpolate unstructured data onto depth levels.
  * A CLI command `convert` to perform the conversion.

2025-02-21 08:54 UTC, mandresm requested changes
In general looks good to me. I only have a few requests.

2025-02-21 08:54 UTC, mandresm commented on src/pymorize/cli.py
> +
It seems that this is not used in the end, can it be cleaned up?

2025-02-21 08:54 UTC, mandresm commented on src/pymorize/cli.py
> +
It seems that this is not used, can it be cleaned up, or finalized?

2025-02-21 08:54 UTC, mandresm commented on src/pymorize/cli.py
> +
It seems that this is not used, can it be cleaned up, or finalized?

2025-02-21 08:54 UTC, mandresm commented on src/pymorize/cli.py
> +cli.add_command(scripts)
It seems that this is not used, can it be cleaned up, or finalized?

2025-02-21 09:42 UTC, pgierz commented on src/pymorize/fesom_1p4/load_mesh_data.py
> +# Original code by Dmitry Sidorenko, 2013
This can be added, yes.

2025-02-21 09:44 UTC, pgierz commented on src/pymorize/cli.py
> +
This is a bit deceptive! I added this to allow users to run specific steps in a standalone fashion without firing up the whole machinery (request by @chrisdane). So, rather than defining the entire pipeline stuff, if you want to run this particular step (fesom1 3D to 2D (node vs level)) you can do that from the command line interface:

```
$ pymorize scripts fesom1 nodes-to-levels <arguments>
```

2025-02-21 09:44 UTC, pgierz commented on src/pymorize/cli.py
> +
as above

2025-02-21 09:44 UTC, pgierz commented on src/pymorize/cli.py
> +
as above

2025-02-21 09:44 UTC, pgierz commented on src/pymorize/cli.py
> +cli.add_command(scripts)
as above

2025-02-21 09:46 UTC, pgierz commented
Added URL, if @mandresm has no other comments, I will merge this later in the afternoon.

2025-02-21 10:09 UTC, mandresm commented on src/pymorize/cli.py
> +
I see

2025-02-21 10:14 UTC, mandresm commented on src/pymorize/cli.py
> +
I looked at these lines again (https://github.com/esm-tools/pymorize/pull/77/files#diff-f7f0ca36502b11f2609ec32f5c6b4d304ab0f7e7e9438a689af344588ef7eaeaR208-R210), now I get it how it works. Thanks for the clarification!

2025-02-21 10:18 UTC, mandresm approved these changes
Can be merged now :) Thanks!

2025-02-21 10:18 UTC, merged